<?php
define('NL',"\n");

define('PANDORA_MYSQL_MAQUINA','127.0.0.1:3306');
define('PANDORA_MYSQL_USUARIO','pandora_read');
define('PANDORA_MYSQL_CLAVE','');
define('PANDORA_MYSQL_BASEDATOS','');

define('REGISTRO_RAIZ',__DIR__.'/'.'var/log/hnx/');

define(TERMICA_RENDIMIENTO,0.6);

define('SENSORES_TERMICA_CAUDAL_NOMBRE','Caudal');
define('SENSORES_TERMICA_TEMPERATURA_ENTRADA_NOMBRE','Temp_In');
define('SENSORES_TERMICA_TEMPERATURA_SALIDA_NOMBRE','Temp_Out');
define('SENSORES_ELECTRICA_INTENSIDAD_1_NOMBRE','Inten_1');
define('SENSORES_ELECTRICA_INTENSIDAD_2_NOMBRE','Inten_2');

